export const sliderItems = [
  {
    id: 1,
    img: 'https://placehold.co/1920x1080?text=Image+1',
    title: 'SUMMER SALE',
    desc: 'GET FLAT 30% OFF FOR NEW ARRIVALS.',
    bg: 'f5fafd',
  },
  {
    id: 2,
    img: 'https://placehold.co/1920x1080?text=Image+2',
    title: 'AUTUMN COLLECTION',
    desc: 'GET FLAT 30% OFF FOR NEW ARRIVALS.',
    bg: 'fcf1ed',
  },
  {
    id: 3,
    img: 'https://placehold.co/1920x1080?text=Image+3',
    title: 'WINTER COLLECTION',
    desc: 'GET FLAT 30% OFF FOR NEW ARRIVALS.',
    bg: 'fbf0f4',
  },
];

export const categories = [
  {
    id: 1,
    img: 'https://placehold.co/940x650?text=Image+1',
    title: 'Category 1',
  },
  {
    id: 2,
    img: 'https://placehold.co/940x650?text=Image+3',
    title: 'Category 2',
  },
  {
    id: 3,
    img: 'https://placehold.co/940x650?text=Image+3',
    title: 'Category 3',
  },
];

export const products = [
  {
    id: 1,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: `599`,
  },
  {
    id: 2,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 3,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 4,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 5,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 6,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 7,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 8,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
  {
    id: 9,
    img: 'https://res.cloudinary.com/dgkbxgdt5/image/upload/v1729610440/perfume.webp',
    title: 'Amber Perfume For Men, Ambery & Warm, Long Lasting',
    quantity: '100ml',
    rating: '4.6 Stars',
    review: '7 Reviews',
    price: '599',
  },
];
