GET http://localhost:5000/api/user/usertest

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username":"Ajas",
  "email":"ajas@gmail.com",
  "password":"123456"
}
